kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: openshift-etcd-backup
  namespace: etcd-backup
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'openshift-etcd-backup:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: >-
        https://github.com/albertofilice/openshift-etcd-backup.git
  runPolicy: Serial